SAP/cloud-sdk

docs/java/release-notes.mdx
Please provide a description of what your change does and why it is needed.
=> release notes for 3.32.0

docs/java/features/rest/clients/scp-workflow-rest-api.mdx
Make Announcement of GA version of Workflow API client lib
=> Make Announcement of GA version of Workflow API client lib

docs/java/features/connectivity/destinations.mdx
Extend destinations docu with localhost setup
=> Extend destinations docu with localhost setup

docs/java/guides/cap-sdk-integration.mdx, sidebars.js
This documentation illustrates how the Cloud SDK can be integrated into an existing CAP app.
=> Add docu about CAP and SDK integration

docs/java/guides/cap-sdk-integration.mdx
Please provide a description of what your change does and why it is needed.
=> Remove superfluous section from CAP docu

docs/java/getting-started.mdx, docs/related-projects/cap.mdx
This PR adds more visibility and better interconnection between the docu sections on CAP, CAP + SDK integration and the getting started guide.
=> Better integrate Docu on CAP integration

docs/js/features/connectivity/destination.mdx
Add Auth types. A quick brush up.
@frank-essenberger , take a look if what I've added makes sense to you.
=> Update to Destinations

docs/js/getting-started.mdx
Merge together with https://github.com/SAP/cloud-sdk-cli/pull/246
=> Change link to project "Piper" pipeline

docs/js/features/odata/common/operations/count.mdx, docs/js/features/odata/odata-v4-client.mdx
Here the documentation for the `count` method in getAll requests.
=> Documentation Count

docs/java/features/rest/generate-rest-client.mdx
Minor format improvement in rest generator document
=> Improve rest generator document

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/features/odata/type-safe-client-odata-v4.mdx
Add further accessor details to documentation.
=> Add further exception accessors

docs/js/getting-started.mdx
=> Fix broken link

.github/PULL_REQUEST_TEMPLATE.md, docs/java/features/odata/generate-client.mdx, docs/java/features/rest/generate-rest-client.mdx, docs/java/guides/cf-deploy.mdx, docs/java/guides/linux-how-to.mdx, docs/java/troubleshooting.mdx, docs/java/video/use-odata-v4-client.mdx, docs/js/faq.mdx, docs/js/features/connectivity/generic-http-client.mdx, docs/js/features/connectivity/proxy.mdx, docs/js/getting-started.mdx, styles/SAP/Products.yml
I applied title case in some cases that the linter did not detect (seems to happen when there are Tabs/TabItems in the document).
I reverted part of the rename of C4C -> SAP Sales Cloud so it now refers to SAP Cloud for Customer where appropriate.
I improved the PR template.
=> Title case

docs/java/features/bapi-and-rfc/overview.mdx
After a couple of tickets, including this documentation link in Cloud SDK as well.
=> Added doc link for JCo with AppRouter

.vale.ini, docs/java/features/bapi-and-rfc/overview.mdx, docs/java/features/connectivity/destinations.mdx, docs/java/features/extensions/extension-library/curconv/currency-conversion.mdx, docs/java/features/odata/generate-client.mdx, docs/java/features/resilience/caching.mdx, docs/java/features/rest/clients/scp-workflow-rest-api.mdx, docs/java/features/rest/generate-rest-client.mdx, docs/java/getting-started.mdx, docs/java/guides/cap-sdk-integration.mdx, docs/java/guides/dependencies.mdx, docs/java/overview.mdx, docs/js/api.mdx, docs/js/features/connectivity/generic-http-client.mdx, docs/js/features/odata/odata-v2-client.mdx, docs/js/features/odata/odata-v4-client.mdx, docs/js/getting-started.mdx, docs/overview/getting-started.mdx
=> Improve vale config

docs/java/features/odata/overview.mdx, docs/java/getting-started.mdx
https://sapjira.wdf.sap.corp/browse/CLOUDECOSYSTEM-8825.
Documentation updated to mention about S/4HANA On prem VDM offered by Cloud SDK.
=> Mention on-premise 2020 VDM

docs/js/features/openapi/overview.mdx
Update sidebar and title to avoid double OpenAPI...
=> Make sidebar display overview

docs/java/faq.mdx, docs/java/getting-started.mdx
The PR adds notes to highlight that we only support servlet based applications on Neo environment and spring applications are not supported out-of-the-box.
=> Added some notes related to spring based projects on Neo platform.

docs/java/features/rest/generate-rest-client.mdx
Removed Swagger from the list of required dependencies.
=> [REST Generator GA] Remove Unused Swagger Dependencies

docs/java/features/odata/type-safe-client-odata-v2.mdx
Correction in deprecated code snippet for odata v2.
=> Correcting OData v2 document

docs/java/features/odata/generic-odata-client.mdx
Basic introduction into the usage of our untyped OData client.
=> Explain Basic OData Client Usage

docs/java/features/resilience/caching.mdx
Update documentation about cache invalidation.
=> [Support] Tenant & Principal Aware Cache Invalidation

docs/components/data/features.js, docs/java/features/odata/generic-odata-client.mdx, docs/java/features/odata/overview.mdx, docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/js/features/openapi/generate-openapi-client.mdx
Add example of implementing Batch read request via generic Odata client
=> Add OData v2 batch example for generic OData client

docs/java/features/resilience/caching.mdx
Add documentation about implicit parameter isolation when clearing caches manually.
Also add a more explicit warning about performance impacts when clearing the entire cache.
=> [Caching] Update Cache Clearance Documentation

docs/js/extension-model.mdx, docs/js/features/eslint-configuration.mdx, sidebars.js
=> Add article on eslint config

docs/java/features/odata/generic-odata-client.mdx
=> Generic client for bound actions and functions

docs/java/release-notes.mdx
=> Release notes Java 3.39.0

docs/js/features/logging.mdx, sidebars.js, styles/Vocab/SAP/accept.txt
Add a small documentation and guide like thing on logging.
=> chore: Add documentation on logging

docs/java/guides/dependencies.mdx
Adding a small note that maven plugin versions need to be managed by the customer.
=> [Java] Add info on maven plugin versions

docs/java/extensions/currency-conversion.mdx
=> Link to the Cur Conv help

src/sap/sdk-data/data.js
=> Fix typos in overview

docs/java/features/rest/generate-rest-client.mdx, docusaurus.config.js, package-lock.json, package.json
Necessary changes to update docusaurus 
=> Update docusaurus to alpha.71

docs/java/features/connectivity/destinations.mdx
Explain how the SDK minimizes runtime overhead of looking up destinations by using caching internally.
=> Add Note About Destination Caching

docs/java/features/odata/type-safe-client-odata-v2.mdx
=> [OData v2] Remove redundant hint

docs/java/guides/tutorial-overview-sdk-java.mdx
=> Remove Neo from Tutorials

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/features/odata/type-safe-client-odata-v4.mdx, docs/js/features/common/custom-request-config-note.mdx, docs/js/features/odata/execute-odata-request.mdx
Add example for pagination parameter.
=> Add code sample for optional pagination parameter

styles/Vocab/SAP/accept.txt
=> allow both xml and XML

docs/components/data/features.js
OpenAPI GA in feature matrix + other fixes
=> OpenAPI GA + other fixes

docs/java/features/odata/type-safe-client-odata-v4.mdx
Add an example of a new API to update a complex property
=> complex-properties

docs/java/guides/cap-sdk-integration.mdx, docs/java/guides/spring-boot-war-deployment.mdx, docs/java/troubleshooting.mdx, docs/js/features/openapi/overview.mdx, package.json
Restructuring the overview page for OpenAPI
=> Update OpenAPI overview

docs/js/release-notes.mdx
Update version 1.25.0 release notes for JS
=> Update version 1.25.0 release notes for JS

docs/java/guides/cap-sdk-integration.mdx
Enhancing the CAP integration guide with the mention on how to decorate asynchronous calls.
=> Enhance CAP guide with decorating asynchronous calls

docs/java/faq.mdx
=> [Java] Mention Attachment Service in FAQ

docs/community/community-call.mdx, docs/js/features/openapi/generate-openapi-client.mdx
I have explicitly added the series registration link inside the [upcoming dates section](https://sap.github.io/cloud-sdk/docs/community/community-call#upcoming-dates-2020) and as an info admonition in OpenAPI generator documentation of JS. Also, added in a word to say that we would enable registering for individual sessions soon.
- [x ] You tested if the documentation still builds (`npm run build`)
- ~[x] You verified all new and changed links still work (changing the `id` or …
=> Update Info about community calls

docs/java/features/odata/type-safe-client-odata-v4.mdx
=> Improve & Extend docs on OData V4 Bound Operations

docs/community/community-call.mdx
Fix issues in an old PR which introduced vale issues.
-~[x] You verified all new and changed links still work (changing the `id` or name of a file can break links)~
-~[x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~
=> Fix vale issues

docs/java/features/connectivity/destinations.mdx
Add a paragraph about how to use the `SAMLAssertion` authentication type.
=> Usage Instructions for SAMLAssertion

docs/java/features/bapi-and-rfc/overview.mdx
Updated exclusion documentation to link to SAP doc.
See https://github.wdf.sap.corp/MA/sdk/issues/5344
=> improved BAPI doc with dependency exclusions

docs/java/release-notes.mdx
=> Java Release Notes for 3.48.0

docs/java/faq.mdx, docs/java/features/multi-tenancy/thread-context.mdx
=> Java: Add FAQ Entry for Spring WebFlux

docs/java/faq.mdx
This PR adds a FAQ entry about how to enable remote debugging on CF.
=> [FAQ] How to Remote Debug a CF App

docs/js/features/connectivity/destination.mdx
=> [JS] Update destination.mdx for supporting `OAuth2JWTBearer`.

docs/java/features/resilience/caching.mdx
=> Fix typos in Cache Filter docu

docs/js/features/connectivity/destination.mdx, docs/js/features/connectivity/generic-http-client.mdx
=> Fix API docs links to the new specs

docs/components/data/features.js
- Typo fixed in note of feature matrix.
- Link fixed by using proper ticks for string interpolation.
=> Fix typo and make string interpolation work

README.md
=> Add budge of reuse scan result.

docs/js/features/connectivity/destination.mdx
We have implemented the flow `OAuth2Password` in [this PR](https://github.com/SAP/cloud-sdk-js/pull/1484).
Here the docs are adjusted.
=> chore:add new flow

docs/java/release-notes.mdx
=> Introduce release notes for Java SDK 3.51.0

docs/js/release-notes.mdx
=> JS: update release notes for 2108 cloud release

docs/java/release-notes.mdx, docs/overview/support.mdx
Bring more clarity behind our support channels and process.
=> Mention support launchpad. Minor rewrite for clarity and style.

docs/components/FeatureTable.js, docs/components/JavaFeatureTable.js, docs/components/JsFeatureTable.js
Better icons in legend
~~- [] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~~
=> Improve feature table legend

docs/java/features/connectivity/destinations.mdx
Introduced a small section on how to get destination loaded via the environment variable to forward the current AuthToken to the target system.
=> Add tip on auth token forwarding

docs/components/FeatureTable.js, docs/components/JavaFeatureTable.js, docs/components/JsFeatureTable.js, docs/components/data/features.js, docs/js/getting-started.mdx
=> Feature matrix update

docs/java/features/connectivity/mtls.mdx
Minor updates in Certificate based Authentication document along with updating the error message.
=> Minor updates in Certificate based Authentication

docs/java/release-notes.mdx
This PR adds release notes for the Java SDK for version 3.53.0
=> [Java] Add release notes for 3.53.0

docs/java/features/connectivity/destinations.mdx
This PR adds a small section about how to setup your development environment in BAS when OnPrem connectivity is needed.
=> [Java] BAS OnPrem connectivity instructions

docs/components/data/features.js
=> Fix broken link in feature matrix

docs/js/features/connectivity/destination.mdx
Add section for forwardAuthToken. See for implementation https://github.com/SAP/cloud-sdk-js/pull/1619.
=> doc for forwarAuthToken

docs/java/environments/sap-btp-environments-overview.mdx, docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx, docs/java/faq.mdx, docs/java/features/connectivity/destinations.mdx, docs/java/release-notes.mdx, docs/js/features/connectivity/destination.mdx, docs/js/overview.mdx
According to this SO question this can be overlooked: https://sap.stackenterprise.co/questions/4731?noredirect=1#comment2108_4731
=> Admonition about content type

docs/java/guides/cap-sdk-integration.mdx, docs/java/troubleshooting.mdx, styles/Vocab/SAP/accept.txt
=> Document How to Exclude CXSDK when working with CAP.

docs/js/features/connectivity/destination.mdx
Since the execute and executeRaw APIs change in v2, this PR contains the tabs approach to show both examples.
=> update v2 docs

docs/js/release-notes.mdx
=> Update release-notes for js

docs/js/release-notes.mdx
As part of customer communications, we require to have comprehensive release notes in one place which is our documentation. The changelog can continue to be published in GH as before.
=> Combined release notes for Core Modules and Libs

docs/js/features/connectivity/on-premise.mdx
add two sentences on local connectivity: https://github.com/SAP/cloud-sdk-js/issues/1856.
=> extend information on local connectivity

docs/js/features/odata/common/function-imports/etag-function-import.mdx
This PR removes a deprecated function and introduces the up-to-date one
=> update deprecated function

docs/java/features/bapi-and-rfc/overview.mdx, docs/java/guides/dependencies.mdx
=> [Java] Extend Dependency Guide with Notes on Buildpack

docs/java/guides/dependencies.mdx, docs/java/release-notes.mdx
=> Add new release notes

docs/js/features/connectivity/destination.mdx
Small fix as the example was not valid JSON
=> Fix example for env destination

docs/java/faq.mdx, styles/SAP/HeadingAcronyms.yml
Added a comment on how the Cloud SDK relates to the Log4Shell vulnerability.
=> Add comment for log4shell vulnerability

docs/java/release-notes.mdx
=> [Java] Release Notes 3.60.0

docs/js/announcing-version-2-beta.mdx, docs/js/features/odata/generate-odata-client.mdx
=> [js] Update version 2 beta guide for deleted generator options

docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
The link is updated to point at our samples repository of the same application.
=> update link to point at samples repo

docs/java/environments/sap-btp-kyma-environment.mdx
Add link to blog post & update format
=> Update Kyma Docs

docs/java/release-notes.mdx
Add release notes for version `3.61.0`.
=> [Java] 3.61.0 Release Notes

docs/js/features/odata/common/batch/changeset.mdx, docs/js/features/odata/common/batch/responses.mdx
The examples did not make clear where the changeset comes from. Added it to the destructuring of the service.
Relates to https://github.com/SAP/cloud-sdk-backlog/issues/515
=> doc: Add "import" for changeset

docs/js/guides/upgrade-to-version-2.mdx
Fixed:
- I removed anchors from headers, they are autogenerated. No need for manual ones. It also prevents the generation of the right-side menu
- One occasion of migrating fixed to upgrade
- Fixed a link to support to actually point at support
=> Fixed minor issues with upgrade guide

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/features/odata/type-safe-client-odata-v4.mdx, docs/js/release-notes.mdx
I have added information about using `excludingFields` during PUT Update request.
=> [Java] Update PUT excluding fields

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/features/odata/type-safe-client-odata-v4.mdx
=> Revert "[Java] Update PUT excluding fields"

docs/js/getting-started.mdx
Migrate the getting started guide from CLI to samples repo
=> Getting started guide

docs/components/FeatureTable.js, docs/components/JavaFeatureTable.js, docs/components/JsFeatureTable.js, docs/components/Table.js
=> Fix rendering of emojies

docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
Added a guide describing how to debug a K8S based application
=> Adding a guide on how to debug a K8S based application

docs/js/features/connectivity/generic-http-client.mdx
Add documentation for default fetchCsrfToken behavior in 2.0
=> Csrf token doc update

docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx, docs/java/environments/sap-btp-kyma-environment.mdx
Update on the K8S and Kyma documentation.
We identified an issue with the JWT verification on IAS+K8S based applications, so that access to the Principal is not possible.
Access to the Tenant is still possible.
=> Add comment on K8S and Kyma Multitenancy

docs/java/release-notes.mdx
Add release notes for version `3.62.0`.
=> [Java] 3.62.0 Release Notes

docs/java/features/multi-tenancy/thread-context.mdx, docs/java/guides/cap-sdk-integration.mdx
This PR adds an explanation on how CAP <-> SDK contexts interact
=> [Java] Add Clarifications on CAP Multitenancy

docs/js/features/connectivity/destination-cache-isolation.mdx, docs/js/guides/how-to-add-resilience.mdx, sidebars.js
Added some information on resilience. This should be merged after this PR: https://github.com/SAP-samples/cloud-sdk-js/pull/92 is in.
=> chore: add some documentation on resilience

docs/java/release-notes.mdx
Add release notes for version `3.63.0`.
=> [Java] 3.63.0 Release Notes

docs/js/release-notes.mdx
=> doc: Release notes

docs/js/release-notes.mdx
=> [js] add release notes for 2.1.0 and 1.54.1

docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx, docs/java/environments/sap-btp-kyma-environment.mdx
To be merged together with #696
=> Update K8S Features Based on Last Release

docs/java/faq.mdx, docs/java/features/odata/generate-client.mdx, docs/js/guides/upgrade-to-version-2.mdx
Added a section describing a possible token validation error and solution options based on feedback from SAP/cloud-sdk-js#2211
=> Add section on possible token validation error

docs/java/environments/sap-btp-kyma-environment.mdx, docs/js/guides/upgrade-to-version-2.mdx, styles/Vocab/SAP/accept.txt
Closes https://github.com/SAP/cloud-sdk-backlog/issues/550
=> chore: add details for import update

docs/java/release-notes.mdx
This PR adds the Java release notes for the latest Cloud SDK release (3.66.0).
=> [Java] Release Notes 3.66.0

docs/java/environments/sap-btp-kyma-environment.mdx, docs/java/features/connectivity/destinations.mdx, docs/java/release-notes.mdx, docs/js/features/odata/generate-odata-client.mdx, docs/js/features/openapi/generate-openapi-client.mdx, docs/js/guides/migrate-sdk-application-from-btp-cf-to-kubernetes.mdx
Update about the local env dev coming from corp SO support issue
=> Tip on local service bindings from support

docs/js/release-notes.mdx
=> Add test headline for DocSearch crawler

docs/js/release-notes.mdx
=> Release notes 2.3.0

docs/js/release-notes.mdx
Reverts SAP/cloud-sdk#778
DON'T MERGE! This PR will be merged after review on Tuesday.
=> Revert "Add test headline for DocSearch crawler"

docs/js/features/connectivity/destination.mdx, docs/js/features/connectivity/generic-http-client.mdx, docs/js/features/odata/common/function-imports/etag-function-import.mdx, docs/js/features/odata/common/function-imports/request-builder.mdx, docs/js/features/odata/v4/action-import.mdx, docs/js/features/odata/v4/filter-one-to-many.mdx, docs/js/features/odata/v4/filter-parent-child.mdx
Fixed some links pointing to the old core packages + removed some unnecessary links.
=> doc: Fix/Remove some outdated links to API Docs

docs/java/features/connectivity/destinations.mdx
The section was updated but the links were not.
=> Fix links according to reworked headers

docs/js/release-notes.mdx
Added release notes for the newest version.
Closes SAP/cloud-sdk-backlog#697
=> Add release notes for JS core version 2.4.0

docs/js/tutorials/getting-started/2-execute-odata-request.mdx
changed a method name from `withCustomHeaders` to `addCustomHeaders`
=> changed a method in js tutorial

docs/java/release-notes.mdx
This PR adds release notes for the Java Cloud SDK version `3.69.0`.
=> [Java] Release Notes 3.69.0

docs/js/features/odata/common/operations/create-as-child-of.mdx, docs/js/features/odata/common/operations/deep-create.mdx, docs/js/features/odata/common/query-parameter/filter-functions.mdx, docs/js/features/odata/common/query-parameter/filter.mdx, docs/js/features/odata/v4/filter-one-to-many.mdx
A small hint is added to notify users that EDM primitive types support all six comparison operators. (+ some tiny grammar fixes)
Closes SAP/cloud-sdk-backlog#488
=> docs(js): update js doc for edm primitive type comparison operators

docs/js/features/connectivity/destination-cache-isolation.mdx
This PR adds documentation on customizable destination caching. 
=> chore: add documentation on custom destination caching

docs/java/features/multi-tenancy/thread-context.mdx, docs/java/guides/cap-sdk-integration.mdx, docs/java/release-notes.mdx
This PR documents the new APIs for async executions. Furthermore, this PR removes the thread lifecycle restrictions.
=> [ThreadContext] Update Async Execution Docs

docs/js/release-notes.mdx
Auto-created by update release notes workflow.
=> Update JS Release Notes

.github/workflows/build_documentation.yml, .github/workflows/release.yml, .husky/pre-commit, .husky/pre-push, package-lock.json, package.json
Use node 16 and update dependencies
=> Update GH actions and dependencies

docs/js/features/odata/generate-odata-client.mdx
Just turn the text reference into a hyperlink
=> Fix link to Transpilation section

docs/js/features/connectivity/generic-http-client.mdx
=> [js] fix: format

docs/js/features/connectivity/proxy.mdx
=> fix tutorial link

docs/js/features/odata/execute-odata-request.mdx, docs/js/guides/upgrade-to-version-2.mdx
=> [js] add troubleshooting for api imports

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/guides/cap-sdk-integration.mdx, docs/java/troubleshooting.mdx
This PR removes all mentions of the Service SDK.
=> [Java V4] Remove Service SDK References

docs/js/tutorials/address-manager/read-addresses.mdx
I modified the code example to use object destructuring when calling the API object businessPartnerApi.
=> [JS] Update code example in #recap-existing-service

docs/js/guides/upgrade-to-version-2.mdx
- use `danger` (in red) instead of `caution` (in yellow)
- use capital case + bold font
- add "bad" keyword as the comments in the code example
=> [js] Make bad examples explicit

docs/js/guides/trust-and-key-stores.mdx
Add the 'mTLS' keyword for better searchability
Related to https://github.com/SAP/cloud-sdk-js/issues/2667
=> Add mTLS keyword

.github/workflows/build_documentation.yml
This introduces auto-merge for dependabot PRs.
=> Introduce auto-merge for dependabot PRs

docs-java/environments/sap-btp-kyma-environment.mdx
We're re-evaluating the kyma support and guidelines. Let's make this transparent in the **outdated** documentation.
=> [Java] Add outdated note to kma

docs-java/features/connectivity/destinations.mdx
Remove deprecated strategy from docs
=> [Java] Destination Retrieval Strategy Update

docs-java/release-notes.mdx, docs-js/features/connectivity/proxy.mdx, docs-js/getting-started.mdx, docs-js_versioned_docs/version-v1/features/connectivity/proxy.mdx, docs-js_versioned_docs/version-v1/getting-started.mdx, docusaurus.config.js
With this PR, docusaurus will throw an error when a broken link is introduced.
Additionally, some broken links were updated.
=> fix: update broken links and throw errors when a broken link is found

docusaurus.config.js
Closes SAP/cloud-sdk-backlog#797.
Remove URLs of partial pages from the search result.
Please also review the `URLs need review` in the below comment. 
=> docs(js): clean up searchable docs

docs-js/features/connectivity/destination-cache-isolation.mdx, docs-js/features/connectivity/destination.mdx, docs-js_versioned_docs/version-v1/features/connectivity/destination-cache-isolation.mdx
Closes SAP/cloud-sdk-backlog#735.
I added some docs based on the user feedback for `registerDesitnation`.
=> docs(js): improve register destination

docs-java/features/multi-tenancy/thread-context.mdx, docs-java/guides/cap-sdk-integration.mdx
This PR adds documentation for passing on arbitrary thread local values.
=> [V4] Thread Context Decorator Update

docs-js/features/logging.mdx
Closes https://github.com/SAP/cloud-sdk-backlog/issues/367
add example of a new function `setGlobalTransports()` in the logging section.
=> docs(js): add new feature `setGlobalTransports()` example

docs-js/features/odata/common/etag.mdx
I corrected this eTag example and updated it to version 2.
=> fix: Fix incorrect etag example

static/js/google2623fe0530579a1c.html
This change should allow us more information on how google indexes the page.
See https://search.google.com/search-console/about and https://support.google.com/webmasters/answer/9008080#html_verification&zippy=%2Chtml-file-upload for details.
=> Verify site ownership for google webmaster tools

docs-js/tutorials/address-manager/change-addresses.mdx, docs-js/tutorials/address-manager/read-addresses.mdx, docs-js/tutorials/getting-started/2-execute-odata-request.mdx, docs-js/tutorials/getting-started/3-deploy-app-to-cf.mdx
Closes https://github.com/SAP/cloud-sdk-backlog/issues/885
This renamed plural `BusinessPatners` to singular `BusinessPatner`
=> [js] rename all `BusinessPartner*s*` to `BusinessPartner`

docusaurus.config.js
Adds a feedback link. Closes https://github.com/SAP/cloud-sdk-backlog/issues/464
=> Add feedback link

STYLEGUIDE.md
=> fix: Fix typo in example

docusaurus.config.js
Add the sample repo link to the footer
=> [js] add sample repo to footer

docs-js/tutorials/getting-started/introduction.mdx
I think this was forgotten in the previous update.
=> fix: Remove notion of pregenerated clients from summary

docs-java/release-policy.mdx
Added dates for end-of-life, i.e. when no longer fixes are being shipped for a version.
=> Advertise release and end-of-life dates

docs-js/tutorials/multi-tenant-application.mdx
The previous link pointed to the wrong line.
=> [js] Fix sample code link

docs-java/getting-started.mdx
=> Fix tutorials link

docs-js/features/connectivity/destination.mdx
Closes https://github.com/SAP/cloud-sdk-backlog/issues/956
=> fix: fix formatting

docs-js/features/connectivity/destination.mdx, docs-js/guides/how-to-use-the-approuter.mdx, docs-js/guides/sdk-in-browser.mdx, docs-js_versioned_docs/version-v2/features/connectivity/destination.mdx, docs-js_versioned_docs/version-v2/guides/how-to-use-the-approuter.mdx, docs-js_versioned_docs/version-v2/guides/sdk-in-browser.mdx
Closes: https://github.com/SAP/cloud-sdk-backlog/issues/898
- Add explicit cases where jwt is mandatory
- Add note about approuter session handling in sdk in browser
=> chore: improve documentation of optional jwt property

docs-js/features/odata/generate-odata-client.mdx, docs-js_versioned_docs/version-v2/features/odata/generate-odata-client.mdx
Update the docs for the generator options that has been deprecated and added.
=> chore: Deprecate and add options #506

docs-js/features/odata/generate-odata-client.mdx
Add doc for verbose option for issue [#977](https://github.com/SAP/cloud-sdk-backlog/issues/977)
=> chore: Add doc for verbose option

docs-java_versioned_docs/version-v3/release-notes/release-notes-75-to-89.mdx
Provides the release notes for the upcoming release 3.78.0.
=> Add release notes for SDK v3.78.0

docs-js/release-notes.mdx, docs-js/release-policy.mdx, docs-js_versioned_docs/version-v2/release-notes.mdx, docs-js_versioned_docs/version-v2/release-policy.mdx
Closes https://github.com/SAP/cloud-sdk-backlog/issues/937.
I removed some information that I found too detailed or duplicate.
I added the announcement link for v3.
Note: I would like to exchange the same file for v2 before merging.
=> chore: improve release policy

docs-java/release-notes/release-notes-0-to-14.mdx
=> [Java] `4.4.0` Release Notes

docs-js/features/connectivity/destination.mdx
Relates to: https://github.com/SAP/cloud-sdk-backlog/issues/1010
Add documentation for the retry option with respect to the get destination by name call doing the token exchange.
=> [JS] Add Retry Documentation

docs-js/features/connectivity/generic-http-client.mdx, docs-js/features/middleware.mdx, docs-js/features/odata/execute-odata-request.mdx, docs-js/features/openapi/execute-openapi-request.mdx, sidebarsDocsJs.js
Relates to: https://github.com/SAP/cloud-sdk-backlog/issues/669
This PR adds some documentation on the middleware in general. The resilience section needs to be updated as well. I will do this once the PRs are merged and the API is 100% solid.
=> [JS] Add Middleware Documentation

docusaurus.config.js
I also updated the colors of the announcement bar.
This is what it looks like:
=> chore: switch light and dark mode depending on system settings

src/theme/NotFound.js
Modified the not found page (404) to mention a few ways to resolve the missing links.
=> chore: Swizzle NotFound page

docs-java/release-notes/release-notes-0-to-14.mdx
This PR adds release notes for the Java version `4.7.0`.
=> [Java] Release Notes for `4.7.0`

docs-java/faq.mdx
=> [Java] Fixed typo

docs-js/features/odata/execute-odata-request.mdx
A previous pull request removed the docs relating to a renamed method.
This PR adds the docs back, now with the correct method
=> [JS] Add setBasePath to the docs

docs-java/faq.mdx, docs-java/support.mdx, docs-java_versioned_docs/version-v3/faq.mdx, docs-js/support.mdx, docs-js_versioned_docs/version-v1/faq.mdx, docs-js_versioned_docs/version-v2/support.mdx, docs/support.mdx
Remove SDK components.
Aligned with Sebastian.
=> chore: remove SDK components

docs-js/features/middleware.mdx, docs-js/features/odata/execute-odata-request.mdx, docs-js/features/openapi/execute-openapi-request.mdx, docs-js/guides/how-to-add-resilience.mdx
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1073
Added a lint to mention that middleware allows varargs. Updated the code example
=> update variable args doc for middleware func

docs-js/guides/how-to-add-resilience.mdx
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1079.
Add the resilience explanation from community call
=> chore: add resilience video

docs-java/release-notes/release-notes-0-to-14.mdx
=> Java 4.9 Release Notes

docs-java/release-notes/release-notes-0-to-14.mdx
=> [java] 4.9 Release Notes, fix links

docs-js/features/mail-client/mail-client.mdx
Noticed some general issues in writing.
=> [JS] Fix minor issues in mail-client docs

docs-js/release-policy.mdx
With this PR, the release page is updated to show that v3 is now GA and v2 is soon to be deprecated.
=> [JS] chore: Update release page

docs-java/release-notes/release-notes-0-to-14.mdx
=> Add release notes for java release 4.10.0

docs-js/features/connectivity/destination.mdx, docs-js/features/odata/common/entity/serialize-entity.mdx
Add documentation for https://github.com/SAP/cloud-sdk-backlog/issues/1058.
=> Add docs on iss + jwt

docs-java/release-notes/release-notes-0-to-14.mdx
- Added release notes for the Java version `4.12.0`.
- Fixed header consistency (## for release title and ### for subsections)
=> [Java] Release Notes for `4.12.0`

docs-java/features/bapi-and-rfc/overview.mdx
=> [java] add jco doc link

docs-java/features/connectivity/destinations.mdx
=> [4.13.0] Mention Forward-User-Token as default strategy.

docs-java/features/connectivity/destinations.mdx
=> Revert "[4.13.0] Mention Forward-User-Token as default strategy."

docs-java/features/connectivity/destinations.mdx, docs-java/release-notes/release-notes-0-to-14.mdx
- Added release notes for the Java version `4.13.0`.
=> [Java] Release Notes for `4.13.0`

docs-java/release-notes/release-notes-0-to-14.mdx, docs-java_versioned_docs/version-v3/features/odata/overview.mdx, docs-java_versioned_docs/version-v3/features/odata/type-safe-client-odata-v2.mdx, docs-java_versioned_docs/version-v3/features/odata/type-safe-client-odata-v4.mdx, docs-java_versioned_docs/version-v3/features/rest/clients/btp-business-rules-rest-api.mdx, docs-java_versioned_docs/version-v3/features/rest/clients/scp-workflow-rest-api.mdx, docs-java_versioned_docs/version-v3/features/rest/overview.mdx, docs-java_versioned_docs/version-v3/release-notes/release-notes-0-to-14.mdx, docs-java_versioned_docs/version-v3/release-notes/release-notes-15-to-29.mdx, docs-java_versioned_docs/version-v3/release-notes/release-notes-30-to-44.mdx, docs-java_versioned_docs/version-v3/release-notes/release-notes-45-to-59.mdx, docs-java_versioned_docs/version-v3/release-notes/release-notes-60-to-74.mdx, docs-js_versioned_docs/version-v1/features/odata/execute-odata-request.mdx, docs-js_versioned_docs/version-v1/features/openapi/execute-openapi-request.mdx, docs-js_versioned_docs/version-v1/features/openapi/overview.mdx, docs-js_versioned_docs/version-v2/features/odata/execute-odata-request.mdx, docs-js_versioned_docs/version-v2/features/odata/generate-odata-client.mdx, docs-js_versioned_docs/version-v2/features/openapi/execute-openapi-request.mdx, docs-js_versioned_docs/version-v2/features/openapi/generate-openapi-client.mdx, docs-js_versioned_docs/version-v2/features/openapi/overview.mdx, docs-js_versioned_docs/version-v2/guides/apihub-download-spec.mdx, docs-js_versioned_docs/version-v2/tutorials/address-manager/read-addresses.mdx, docs-js_versioned_docs/version-v2/tutorials/getting-started/2-execute-odata-request.mdx, docs-js_versioned_docs/version-v2/tutorials/getting-started/introduction.mdx, styles/SAP/Products.yml
Follow up from
https://github.com/SAP/cloud-sdk/pull/1365
=> Rename API Business Hub

docs-java/features/connectivity/http-client.mdx
=> Fix: a typo

docs-java/features/connectivity/destinations.mdx, docs-java/features/connectivity/mtls.mdx
Documenting how to configure security configuration while building a destination.
- ~[x] Verify links still work, e.g., if `id` or the name of a file is changed.~
- ~[x] Update the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js), e.g., if a feature is added.~
=> [Java] Add documentation about mtls feature

docs-java/features/bapi-and-rfc/overview.mdx
=> Update JCo deprecation warning

docs-java/release-notes/release-notes-15-to-29.mdx
Release notes for Java SDK version `4.16.0`.
=> Chore: Java SDK `4.16.0` Release Notes

docs-java/features/connectivity/destinations.mdx
=> Document sap-language handling

docs-java/guides/dependencies.mdx
Add a warning for the deprecation of the SJB BOM.
=> Deprecate SJB BOM

docs-java/release-notes/release-notes-15-to-29.mdx
Release notes for Java SDK version `4.17.0`.
=> Java SDK `4.17.0` Release Notes

docs-java/faq.mdx, docs-java/getting-started.mdx, docs-java/overview.mdx, src/components/data/features.js
See [Deprecated NEO #8180](https://github.wdf.sap.corp/MA/sdk/pull/8180#top)
=> `4.17.0 Relevant` Deprecated NEO

docs-js/features/connectivity/on-premise.mdx
This PR updates the documentation to include new header `x-sap-security-session: create` in SAMLAssertion.
=> chore: update doc to indicate saml assertion header change

docs-java/release-notes/release-notes-15-to-29.mdx
Release notes for Java SDK version `4.19.0`.
=> Java SDK `4.19.0` Release Notes

docs-java/environments/kyma.mdx, docs-java_versioned_docs/version-v5/environments/kyma.mdx
This PR adds a few sentences about our Kyma support.
=> Java: Clarify how to use the SDK on Kyma

docs-java/environments/gardener.mdx, docs-java/environments/kyma.mdx, docs-java_versioned_docs/version-v5/environments/gardener.mdx, docs-java_versioned_docs/version-v5/environments/kyma.mdx
Update guides to versions 1.3.0 and 2.9.2 of TP / CP
=> Update K8S docs for latest releases of Unified Connectivity

docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
I felt that the module is too niche to justify putting details into the migration guide. I would instead link to the release notes (which contain more info) once they are available.
=> [V5] Migration Guide: Security Servlet Removal

docs-java/release-notes/release-notes-15-to-29.mdx
=> [Java] Release notes 4.21.0

docusaurus.config.js
=> add redirect

docs-java/features/odata/v2-client.mdx, docs-java/features/odata/v4-client.mdx
Mention JSR-305 dependency requirement.
=> [Java] Reference jsr305 dependency in OData VDM projects

docs-java/features/odata/v2-client.mdx, docs-java/features/odata/v4-client.mdx
=> Revert "[Java] Reference jsr305 dependency in OData VDM projects"

docs-java/faq.mdx, docs-java/features/connectivity/destinations.mdx, docs-java_versioned_docs/version-v5/faq.mdx, docs-java_versioned_docs/version-v5/features/connectivity/destinations.mdx
Adding few updates to documentation from support issues.
=> [Java] Updates from Support issues

docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
Mention replacement/workaround for `AuthTokenBuilder`
=> [V5] Migration Guide: AuthTokenBuilder Removal

docs-java/release-notes.mdx, docs-java_versioned_docs/version-v3/release-notes.mdx
This PR fixes our outdated notice about SDK v3 being in "maintenance" mode.
=> Java: Fix Maintenance Notice About V3

docs-java/release-notes.mdx, docs-java/release-notes/release-notes-15-to-29.mdx, docs-java_versioned_docs/version-v5/release-notes.mdx
This PR contains the release notes for the Java SDK version `4.22.0`
=> Java: Release Note for `4.22.0`

docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
This PR adds some documentation on how to use our generators from the cli after we removed the cli modules.
=> Add docs for removal of cli modules

docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
=> Java: Fix Formatting of Details Block

docs-js/guides/how-to-use-the-approuter.mdx, docs-js_versioned_docs/version-v1/guides/how-to-use-the-approuter.mdx, docs-js_versioned_docs/version-v2/guides/how-to-use-the-approuter.mdx
This PR fixes the Approuter manifest yaml.
=> fix: approuter manifest yaml docs

docs-js/guides/how-to-use-the-approuter.mdx, docs-js/overview.mdx, docs-js_versioned_docs/version-v1/guides/how-to-use-the-approuter.mdx, docs-js_versioned_docs/version-v2/guides/how-to-use-the-approuter.mdx
Related to: https://github.com/SAP/cloud-sdk/issues/1554
=> Fix: feature matrix link

docs-java/features/rest/overview.mdx, docs-java/getting-started.mdx, docs-java_versioned_docs/version-v3/features/rest/overview.mdx, docs-java_versioned_docs/version-v3/getting-started.mdx, docs-java_versioned_docs/version-v5/features/rest/overview.mdx, docs-java_versioned_docs/version-v5/getting-started.mdx, docs/support.mdx
In the previous [PR](#1526), we updated the support board link.
We should do the same for the overview page.
=> [java] Update support board link for overview page

docs-java/features/bapi-and-rfc/overview.mdx, docs-java_versioned_docs/version-v5/features/bapi-and-rfc/overview.mdx
=> [java] Update RFC deprecation notes

docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
=> Add migration note for `PrincipalPropagationStrategy`

docs-java/release-policy.mdx, docs-java_versioned_docs/version-v5/release-policy.mdx
=> [Java] Update release policy

docs-java/release-notes/release-notes-15-to-29.mdx
This adds the release notes for the latest SDK v4 release.
=> [Java] Add release notes for 4.26.0

docs-java/features/bapi-and-rfc/overview.mdx
Close: https://github.com/SAP/cloud-sdk/issues/1592
=> chore: add links to node and python rfc libs

docs-java/release-notes/release-notes-15-to-29.mdx
This adds the release notes for the latest SDK v4 release.
=> [Java] Add release notes for 4.27.0

docs-java/features/connectivity/destinations.mdx
=> fix: BAS link

docs-java/release-notes/release-notes-0-to-14.mdx
Release notes for the Java SDK version `5.1.0`.
=> feat: add release notes for Java SDK version 5.1.0

docs-java/features/connectivity/001-btp-destination-service.mdx
This PR refactors our connectivity documentation to mention our new API (introduced in `5.1.0`) for destination property retrieval.
=> refactor: destination property retrieval

docs-java/features/connectivity/001-btp-destination-service.mdx, docs-java/features/connectivity/004-http-destinations.mdx
This PR fixes some small left-overs that were noticed during our last sprint review.
=> fix: Java Connectivity Leftovers

docs-java/release-policy.mdx
=> chore: update v4 EoL

docs-js/features/mail-client/mail-client.mdx
=> chore: Add docs on mail-client debug options

docs-java/release-notes/release-notes-0-to-14.mdx, docs-java_versioned_docs/version-v4/release-notes/release-notes-15-to-29.mdx
Release notes for the Java SDK version `5.2.0`.
=> feat: add release notes for Java SDK version 5.2.0

docs-js/features/mail-client/mail-client.mdx
=> [js] chore: update mail client notes

docs-java/release-notes/release-notes-0-to-14.mdx
Release Notes for the Java SDK 5.3.0
=> feat: add release notes for Java SDK version 5.3.0

docs-js/guides/trust-and-key-stores.mdx
Add note on `.pem` support. Closes https://github.com/SAP/cloud-sdk-backlog/issues/1178.
=> chore: Add .pem support note

docs-js/features/mail-client/mail-client.mdx
Closes https://github.com/SAP/cloud-sdk/issues/1709
=> chore: Fix link in mail-client docs

docs-java/features/connectivity/005-http-client.mdx
Fixes SAP/cloud-sdk-java/issues/336
=> fix: HTTP Client 5 Link

.github/workflows/build_documentation.yml, .github/workflows/release.yml
Upgrade build workflow to use node 20
=> chore: upgrade node

docs-java/features/connectivity/003-service-bindings.mdx, docs-java/features/connectivity/007-mtls.mdx
⚠️ Only merge after 5.7.0 and after #1755 ⚠️
=> [Java] Add Docs on Zero Trust

docs-java_versioned_docs/version-v4/release-notes/release-notes-15-to-29.mdx
Added release notes for Cloud SDK for Java 4.31.0
=> Java v4.31.0 release notes

docs-java/features/connectivity/003-service-bindings.mdx
=> Remove tenant ID from IAS callback variant

docs-java_versioned_docs/version-v4/release-notes.mdx, docs-java_versioned_docs/version-v4/release-notes/release-notes-15-to-29.mdx
Added release notes for Cloud SDK for Java 4.32.0
=> Java v4.32.0 release notes

docs-java/release-policy.mdx
=> Remove EoL for java v5

docs-java/release-policy.mdx
=> Mark java v4 as deprecated

docs-java/features/odata/v2-client.mdx, docs-java/features/odata/v4-client.mdx
Added a workaround that a customer needed https://github.com/SAP/cloud-sdk-java/issues/379
=> Added CSRF Workaround

docs-java/features/rest/overview.mdx
Changed:
> Why Using SAP Cloud SDK for Java With OpenAPI Services?
to
> Why Use the SAP Cloud SDK for Java With OpenAPI Services?
=> Fix Typo in Java OpenAPI Overview

docs-java/release-notes/release-notes-0-to-14.mdx
=> Add release note to old version `5.13.0` for incompatibility of Apache5 and SCC

docs-js/release-notes.mdx
=> Update Release Notes JS

src/components/data/features.js
=> [Java] Update feature scope for neo

docs-js_versioned_docs/version-v3/features/mail-client/mail-client.mdx
=> chore: update mail client deprecation notes

docs-java/overview.mdx, docs/about.mdx
=> [java] Update License information

docusaurus.config.js, src/theme/SearchBar/index.js, src/theme/SearchBar/styles.css
The search bar now only returns results relevant to Java or Javascript depending on the current page.
=> Fix: Algolia search bar

src/components/data/features.js
=> [js] Update feature scope

docs-js/release-policy.mdx, docusaurus.config.js
=> [js] Update release policy

docs-js/release-notes.mdx
Enabling destination cache moved to "improvement"
=> [js] Improve release notes

docs-js/guides/upgrade-to-version-4.mdx
=> chore: Update guide

.github/workflows/release.yml, CONTRIBUTING.md, docusaurus.config.js, package-lock.json, package.json
https://github.com/SAP/ai-sdk-js-backlog/issues/266
The Algolia API key should not be public
=> Algolia key in environment variable

.github/workflows/release.yml, CONTRIBUTING.md, docusaurus.config.js, package-lock.json, package.json
This reverts commit 847b9e2a1a8b3deccdd4c18ebee0cfec504869cc.
The algolia key is public. It also can be accused from network traffic when searching on the website
=> Revert "Algolia key in environment variable (#2056)"

docs-java/overview.mdx
=> Update Java supported Versions

docs-java/guides/5.0-upgrade-steps.mdx
=> fix: [Java] Fix broken link in update guide

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/feedback.md, .github/ISSUE_TEMPLATE/issue.md, docusaurus.config.js
=> chore: Remove survey links

docs-js/features/connectivity/csrf.mdx, docs-js_versioned_docs/version-v3/features/connectivity/csrf.mdx
=> chore: Remove csrf note
