docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/features/odata/type-safe-client-odata-v4.mdx
Extends the OData documentation with supported update strategies as we had seen some confusion about it lately.
=> Add docu about odata update strategies

docs/devops/getting-started.mdx, docusaurus.config.js, sidebars.js
Mark SDK for CI/CD as deprecated and link gpp guide
=> Mark SDK for CI/CD as deprecated and link gpp guide

docs/java/features/odata/generate-client.mdx
This PR adds a warning to override the service path if the generated default is not matching expectations.
based on customer feedback e.g. https://stackoverflow.com/questions/64807793/unable-to-use-vdm-generator-with-cap-for-gwsample-basic-service
=> Add warning about setting the service path for geneterated OData classes

docs/js/features/connectivity/destination.mdx
to help developers set up their local development environment.
Example taken from:
https://sap.github.io/cloud-s4-sdk-book/pages/mock-odata.html
Please provide a description of what your change does and why it is needed.
=> Add sample for the `destinations` env. variable

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/features/odata/type-safe-client-odata-v4.mdx
Documentation for the upcoming experimental server-driven paging feature of Cloud SDK.
Planned release date: 4th of December.
Sources
https://www.odata.org/documentation/odata-version-2-0/json-format/
https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ServerDrivenPaging
=> Server-Driven Paging

docs/java/features/rest/generate-rest-client.mdx
Removed unnecessary dependency spring-context from the rest generator document 
=> Removed unnecessary spring-context dep from Rest Generator guide

docs/java/features/bapi-and-rfc/overview.mdx, docs/java/troubleshooting.mdx
Adds a note in the BAPI docs that for multi-threading or resilience a dependency scope change is needed when using the SAP Java Buildpack. Also adds an entry under the troubleshooting guide.
=> Add note on dependency scope change for multi tenancy with BAPI

docs/js/features/connectivity/destination.mdx
Added a section for destintaion lookup using the issuer field.
=> Adjust documentation for destination look via issuerlinter prettier

docs/components/data/features.js
I decided to add MDI to the feature-matrix so that internal customers who look into it are aware it exists.
=> Add MDI to feature-matrix

docs/java/features/rest/clients/scp-workflow-rest-api.mdx, docs/js/features/openapi/generate-openapi-client.mdx
There is a new API `ScpCfServiceDestinationLoader.getDestinationForService` introduced
that creates a `Destination` programmatically using values read from `VCAP_SERVICES` for Workflow service.
PR: https://github.wdf.sap.corp/MA/sdk/pull/4847
- ~[x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~
=> Update SCP Workflow REST API with Destination retrieval change

docs/java/features/bapi-and-rfc/overview.mdx
Added a section in BAPI Local deployment to set the destinations environment variable. 
WRT to this SO Issue: https://stackoverflow.com/questions/65806231/the-destination-could-not-be-found-when-calling-bapi-locally-with-cloud-sdk-spri
=> Update BAPI Document

docs/java/features/connectivity/destinations.mdx
Add documentation on how to configure the TimeLimiter timeout when using the `ScpCfDestinationLoader`.
=> [Support] Configurable Timeout in ScpCfDestinationLoader

docs/java/release-notes.mdx
I have added the right javadoc link in the release notes for version 3.37.0 
=> Update javadoc link

docs/java/features/connectivity/destinations.mdx
To avoid confusion, let's publicly declare the default behavior for retrieving destinations.
=> Indicate default destination retrieval strategy

docs/js/features/connectivity/destination.mdx
closes: #31 
Added the import and put the right method name. The `setDestination()` method is the exported one.
=> Small update on setDestination()

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/features/odata/type-safe-client-odata-v4.mdx, docs/java/features/rest/generate-rest-client.mdx
Add an info note about retrieving an entity first before updating. See: https://stackoverflow.com/questions/66573358/attempt-to-create-simple-contact-gives-error-patch-requests-require-components
=> Add info about retrieving entities before updating

docs/java/features/odata/type-safe-client-odata-v2.mdx
In the upcoming release additional API is being introduced for OData V2 batch.
=> [3.41.0] OData v2 Batch Read API

docs/java/features/multi-tenancy/thread-context.mdx, docs/js/extensions/currency-conversion.mdx, package-lock.json
After some investigation (together with @MatKuhr) we found out that the `AuthTokenAccessor.executeWithAuthToken` really only replaces the AuthToken, but not the derived properties, like Tenant and Principal.
Therefore we deemed it necessary to extend the documentation with that information.
=> Add section on ThreadContext propagation details

docs/java/guides/cf-xsuaa.mdx
When reiterating the document, I noticed that for XSUAA in our test subaccount on Cloud Foundry, I had to add `uaa.user` scope to my authorization flow.
=> Mention `scope=uaa.user` case for `Unauthorized` XSUAA response

docs/js/features/connectivity/generic-http-client.mdx, docs/js/features/odata/common/index.jsx, docs/js/features/odata/common/skip-csrf-token-example.mdx, docs/js/features/odata/common/skip-csrf-token.mdx, docs/js/features/odata/odata-v2-client.mdx, docs/js/features/odata/odata-v4-client.mdx
=> csrf token updates

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/troubleshooting.mdx
Add usage documentation for the new `addChangeSet` API on ODataV2 Batch services.
=> [ODataV2] Add Docu for new `addChangeSet` Api

styles/Vocab/SAP/accept.txt
I think the SDK should be accepted as a shorter form of referring to the SAP Cloud SDK.
In many situations using "SAP Cloud SDK" gets annoyingly verbose and out of style with good writing principles.
=> accept SDK

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/release-notes.mdx, docs/java/troubleshooting.mdx, docs/js/features/odata/common/function-imports/entity-return-type.mdx, docs/js/features/odata/common/function-imports/index.jsx, docs/js/features/odata/common/query-parameter/filter-functions.mdx, docs/js/features/odata/common/query-parameter/filter.mdx, docs/js/features/odata/odata-v2-client.mdx, docs/js/features/odata/odata-v4-client.mdx
Add a troubleshooting section for explaining the missing `execute` method for some function/action imports and suggest to use `executeRaw` instead.
=> Troubleshooting for the missing `execute` in some function/action imports.

docs/js/features/cli/generator.mdx, docs/js/features/cli/init.mdx, docs/js/features/cli/overview.mdx, docs/js/features/cli/package.mdx
The announcement in docs to deprecate the CLI
=> Deprecate CLI

docs/java/guides/spring-boot-war-deployment.mdx
Fix two typos in the docu about the WAR deployment.
=> Fix typos in WAR deployment guide

docs/java/features/odata/generate-client.mdx
Add documentation on how to configure the name source.
=> [OData Generator] Add Documentation for the NameSource Parameter

src/sap/sdk-js/BuildBadge.js
Make the link from the badge pointing at JS repo, not the docs. The actual source from the badge is correct.
=> Fix the link on the badge to point to JS repo

docs/java/features/odata/generate-client.mdx
This PR reflects the latest refactoring of the name generation logic in both OData generators.
=> Update OData (V2 + V4) Generator Usage Instructions

docs/java/features/bapi-and-rfc/overview.mdx
As a learning from an [internal issue](https://github.wdf.sap.corp/MA/sdk/issues/5344) we found that the additional exclusion of `java-security` library is necessary.
=> Mention dependency exclusion

docusaurus.config.js
Remove constant that was introduced to disable to the `DocVersionBanner` component on top of our articles. However, it turned out that this was not actually needed.
=> Remove Unneeded Constant

docs/community/community-call.mdx, docs/js/features/openapi/generate-openapi-client.mdx
I have removed the invite links to our old community call 
- You followed [naming center](https://www.sapbrandtools.com/naming-center/#/dashboard) guidelines when referring to SAP products (e.g. SAP S/4HANA)~
=> Remove old community call links

docs/java/release-notes.mdx
Update the link to our Javadoc in our release notes.
=> Update link to Javadoc in release notes

docs/java/features/connectivity/destinations.mdx
Minor left over from the time when I initially created that documentation.
=> Add link to the ScpCfDestinationTokenExchangeStrategy Javadoc

.reuse/dep5, LICENSE, LICENSES/Apache-2.0.txt
Created the file .reuse/dep5 in the root of the project to bulk-license the directory.
=> Add dep5 to bulk license all files

docusaurus.config.js, package-lock.json, package.json
Docusaurus now builds with Webpack 5 which requires some Node APIs to be explicitly polifilled. Otherwise, the build fails.
~~- [x] You have updated the [feature matrix](https://github.com/SAP/cloud-sdk/blob/main/docs/components/data/features.js) if you add documentation on a new feature or otherwise required.~~
=> Fix build for Webpack 5

docs/js/features/connectivity/generic-http-client.mdx
Related to [this issue](https://github.com/SAP/cloud-sdk/issues/454)
- add some links to `destination object` and `DestinationNameAndJwt`
- mention JWT is optional and show the JWT doc
=> Improve generic http client doc

docs/java/release-notes.mdx
=> [Java] Update Javadoc links in Release Notes

docs/java/features/connectivity/http-client.mdx
There is no class called DestinationAccess, it should be DestinationAccessor
When i was trying to use the sample code, i found the issue, i think it is a typo error
There is no class called DestinationAccess, it should be DestinationAccessor
=> DestinationAccess changed to DestinationAccessor

docs/java/features/rest/generate-rest-client.mdx
Added a section explaining when compilation error occurs while input specification contains keywords `anyOf/oneOf`
=> [OpenAPIGenerator] Add section about issues during `anyOf/oneOf`

docs/related-projects/piper.mdx
Regarding https://sap.github.io/cloud-sdk/docs/related-projects/project-piper
The video is now longer available and probably not needed.
=> Remove reference to no longer available video

docs/java/features/odata/type-safe-client-odata-v2.mdx, docs/java/features/odata/type-safe-client-odata-v4.mdx
Add a short section with required dependencies for both the OData v2 and v4 typed clients.
=> [Java] Add Prerequisites for OData v2/v4 Typed Clients

docs/java/environments/sap-btp-kubernetes-environment-with-sap-gardener.mdx
This PR adds a section on how to adjust the xsuaa binding create by the service catalog to be consumable by the SDK.
=> Provide documentation on how to adapt service catalog bindings

docs/java/features/service-bindings/service-binding-loader.mdx
This PR introduces a new section on our feature description of the "Service Binding Loader", which explains how consumers can easily tweak and adjust this feature.
Right now, the only entry focuses on the configuration of the root location from which the service bindings should be read.
=> [Java] Configuration of Service Binding Root Location

docs/js/release-notes.mdx
This PR is re-created, as the [old PR](https://github.com/SAP/cloud-sdk/pull/640) failed due to magic vale issue. 
The vale issue was also reported by others [here](https://github.com/errata-ai/vale-action/issues/48)
=> [js] Add release notes for 1.53.1

docs/java/features/odata/generate-client.mdx
This PR adds documentation for the `keepExistingSignatures` feature of our OData generators.
=> [Java] KeepExistingSignatures Feature for OData Generators

docs/java/release-policy.mdx
I assume this should read "compatibility".
=> Fix typo in Java release policy

docs/js/features/odata/common/function-imports/request-builder.mdx
Ref: SAP/cloud-sdk-js#2395
Closes: SAP/cloud-sdk-backlog#73
Add the documentation for `dataAccessor` used in function / action import.
=> docs(js): add `dataAccessor` for function / action import

docs/js/tutorials/address-manager/change-addresses.mdx, docs/js/tutorials/address-manager/read-addresses.mdx, docs/js/tutorials/getting-started/1-set-up-dev-environment.mdx, docs/js/tutorials/getting-started/2-execute-odata-request.mdx, docs/js/tutorials/getting-started/3-deploy-app-to-cf.mdx, src/css/custom.css, styles/Vocab/SAP/accept.txt
- Aligned the sections between both tutorials
- Added css class for max-height+scroll for code files tabs
PS: A better way to handle styling would be to add below in `custom.css` instead
```
[class*='codeBlock'] {
max-height: 30em
}
```
But this also affects java code snippets.
=> chore: align tutorials

docs/java/features/multi-tenancy/thread-context.mdx, docs/java/release-notes.mdx, docs/js/guides/upgrade-to-version-2.mdx, docs/js/release-notes.mdx
This PR adds a comment in our mdx file that will be used to make our release-notes automation parsing more readable and therefore less cryptic.
(Also running prettier catched some previously wrong code)
=> chore: Make release-notes automation parsing more readable

docs/js/features/logging.mdx
Closes SAP/cloud-sdk-backlog#380
Update js docs `logging.mdx`. Relates to SAP/cloud-sdk-backlog#380, SAP/cloud-sdk-js#2481.
=> docs(js): update logging.mdx

docs/js/release-notes.mdx
Just added a `s` for some heading in the release notes.
=> [js] Pluralize headings release Note

docs/java/features/connectivity/destinations.mdx, docs/java/features/multi-tenancy/thread-context.mdx
This PR removes all mentions of the `RequestScopedHttpClientCache`, which will be removed from the Cloud SDK for Java in version 4.
=> [Java V4] Remove `RequestScopedHttpClientCache`

docs-js/release-notes.mdx
The rautomatic release note update failed: https://github.com/SAP/cloud-sdk-js/runs/7356882863?check_suite_focus=true
Manual copy of the release notes.
=> [JS] manual release note update

docs-js/tutorials/address-manager/read-addresses.mdx
"Built-in" is correct for what we want to say here, cf [1](https://www.merriam-webster.com/dictionary/built-in), [2](https://www.merriam-webster.com/dictionary/build%20in)
Fixed spelling of "built-in"
=> chore: Fix spelling

docs-js/features/connectivity/destination-cache-isolation.mdx
We had a typo using the term `UserTenant` instead of `TenantUser` reported here: https://github.com/SAP/cloud-sdk/issues/935
This PR fixes this.
=> Fix typo UserTenant 

src/theme/NavbarItem/DropdownNavbarItem.js
For some reason the exact same path doesn't resolve unless you hit refresh (for example, click on an API Reference Link -> Page not found -> simply refresh the page), I assume this has something to do with the router of Docusaurus. Either way, the hotfix for this is simply using an absolute path.
Note that this is not optimal for local testing, as the reference won't be dynamic enough anymore to point at the local reference.
On the plus side though, with the absolute path, a new window is opened when clicking on an API reference, which is better UX I believe.
=> fix: api reference links

docs-java/getting-started.mdx, docs-java/guides/dependencies.mdx, styles/Vocab/SAP/accept.txt
In V4 we introduced a new BOM that combines the SAP Java Buildpack BOM for TomEE, as well as our `sdk-bom`.
This allows consumers to easily consume a tested combination of dependency versions and scopes.
Especially in the archetypes that requires some changes to be able to run the application locally.
This required now some changes on our documentation.
=> Java/actually v4/mention sjb bom

docs-java/features/multi-tenancy/thread-context.mdx, docs-java/features/resilience/caching.mdx, docs-java/guides/cap-sdk-integration.mdx
This PR adds "danger boxes" about the current limitations with regard to the `executeWith...` API, especially in combination with the CAP integration.
=> [V4] Add Warnings about `executeWith...` Limitations

docs-js/features/odata/v4/filter-one-to-many.mdx, docs-js/features/odata/v4/filter-parent-child.mdx
The example shown in the 1-to-N nav properties for `any` and the generated filter url expression is incorrect. This PR corrects that.
=> fix: correct any lambda operation example

docs-js/release-policy.mdx, sidebarsDocsJs.js
Those pages are not accurate anymore so they might lead to confusion.
=> Remove pre-release info on sdk v2

docusaurus.config.js
I added the edit link that got lost in the docs layout change.
=> fix: Add edit link on Java and JS pages

docs-js/release-notes.mdx
Relates to: https://github.com/SAP/cloud-sdk-backlog/issues/841
Add the link manuall for the already existing released veriosn.
With thie [PR](https://github.com/SAP/cloud-sdk-js/pull/2889) it should be done automatically from now on.
=> chore: Adjust existing release notes

docs-java/release-notes.mdx, docs-js/release-notes.mdx
This PR adds release notes for the SAP Cloud SDK for Java release of version 3.75.0.
To be merged on September 23, 2022.
=> [Java] Release Notes for `3.75.0`

docs-java/features/connectivity/destinations.mdx
This PR replaced the removed `SUBSCRIBER_THEN_PROVIDER` destination retrieval strategy with the new `CURRENT_TENANT_THEN_PROVIDER` one.
=> [Java V4] Replace Removed Destination Retrieval Strategy

docs-java/features/connectivity/destinations.mdx
This PR replaces the deprecated destination retrieval strategy `SUBSCRIBER_THEN_PROVIDER` (for both Cloud Foundry and Neo) with the new `CURRENT_TENANT_THEN_PROVIDER` strategy.
**DON'T MERGE THIS UNTIL CLOUD SDK 3.76.0 IS RELEASED.**
=> [Java V3] Replace Deprecated Destination Retrieval Strategy

docusaurus.config.js
Both the versioned v3 and current v4 java docs can be displayed using the dropdown.
=> Add version dropdown for Java v3 and v4

docs-java/release-notes.mdx
This PR adds a short notice about the known vulnerability CVE-2022-42003 that affects a version of `jackson-databind` that is shipped by the SDK.
=> [Java V4] Add Note About CVE-2022-42003

src/pages/components/HomepageFeatures.js, src/pages/index.js
use description meta tag for snippet generation
The home [page](https://sap.github.io/cloud-sdk/) shows wrong snippets:
=> [js] use description meta tag for snippet generation

docs-js/guides/how-to-add-resilience.mdx, docs-js_versioned_docs/version-v1/guides/how-to-add-resilience.mdx
I've fixed the broken links to the resilience example
=> fix broken links in resilience documentation to resilience example

docs-js/features/connectivity/destination.mdx
Removed references to `ServiceBinding`. Changed it to `Service` instead
=> chore: fix service binding link

docs-java_versioned_docs/version-v3/release-notes/release-notes-75-to-89.mdx
This PR adds release notes for the SAP Cloud SDK for Java release of version 3.76.0.
To be merged on October 31, 2022.
=> [Java] Release notes for `3.76.0`

docs-js/guides/bas-external-system.mdx, docs-js_versioned_docs/version-v2/guides/bas-external-system.mdx
Update the broken tutorial links in the BAS guide
=> fix: tutorial link in BAS guide

docs-js/features/connectivity/generic-http-client.mdx
Updated docs to match [current implementation](https://github.com/SAP/cloud-sdk-js/blob/main/packages/http-client/src/http-client.ts#L351) of the function.
=> Adapt to new signature of executeHttpRequest function

docs-java/features/multi-tenancy/thread-context.mdx
Added new instructions to propagate the Spring `SecurityContext` to `@Async` calls.
- Removed a redundant tip
- Fixed grammar
- Added the new instructions in a tip
=> Added Spring SecurityContext instructions

docs-java/guides/4.0-upgrade.mdx
With a [support issue](https://github.com/SAP/cloud-sdk/issues/1187), we realised that we [had removed](https://github.wdf.sap.corp/MA/sdk/pull/7088) some public legacy classes from version 4 without deprecating them.
This PR acknowledges that these classes were removed in version 4.
=> [Java] Update migration guide with deleted classes

docs-js_versioned_docs/version-v2/release-notes.mdx
Turns out our automation adds the release notes not to the page that is visible by default
=> Add release notes for version 2.13.0 and 2.12.1

docs-js/features/odata/common/batch/responses.mdx, docs-js/features/odata/common/batch/retrieve-request.mdx, docs-js/features/odata/v2/changeset-example.mdx, docs-js/features/odata/v2/request-builder.mdx, docs-js/features/odata/v4/changeset-example.mdx, docs-js/features/odata/v4/request-builder.mdx, docs-js_versioned_docs/version-v2/features/odata/common/batch/responses.mdx, docs-js_versioned_docs/version-v2/features/odata/common/batch/retrieve-request.mdx, docs-js_versioned_docs/version-v2/features/odata/v2/changeset-example.mdx, docs-js_versioned_docs/version-v2/features/odata/v2/request-builder.mdx, docs-js_versioned_docs/version-v2/features/odata/v4/changeset-example.mdx, docs-js_versioned_docs/version-v2/features/odata/v4/request-builder.mdx
In this PR I renamed the `actionImports` and `functionImports` to `operations`.
=> chore: rename `actionImports` and `functionImports` to `operations`

src/pages/components/HomepageFeatures.js
Relates: https://github.com/SAP/cloud-sdk-backlog/issues/1022
As discussed here: https://github.com/SAP/cloud-sdk-backlog/issues/1022 we are the JavaScript SDK. So we removed the (and TypeScript) consistently.
=> chore: Remove the (and TypeScrip)

docs-js/features/odata/execute-odata-request.mdx, docs-js/features/odata/generate-odata-client.mdx, docs-js/tutorials/getting-started/2-execute-odata-request.mdx
Update servicePath docs after removing VALUE_IS_UNDEFINED
=> chore: remove `VALUE_IS_UNDEFINED` from OData `servicePath` docs

docs-java/features/multi-tenancy/thread-context.mdx
Latest troubleshooting session with a customer resulted in the clear recommendation for `ExecutorService` to use `invokeAll`, instead of looping via `submit`.
=> Motivate `ExecutorService#invokeAll`

docs-js/features/odata/execute-odata-request.mdx, docs-js/features/odata/generate-odata-client.mdx, docs-js/tutorials/getting-started/2-execute-odata-request.mdx
Changes the docs relating to the removed `servicePath` parameter to `basePath`.
Also removes a docs section regarding a method that doesn't exist.
=> chore: change servicePath docs to basePath

docs-js_versioned_docs/version-v2/tutorials/multi-tenant-application.mdx
Add missing `}` in the TS Multi-Tenancy guide.
=> Fix typo in TS Multi-Tenancy Guide

docusaurus.config.js
The PR switches the default path for docs to v3
=> chore: Make v3 docs the default

docs-js/features/odata/generate-odata-client.mdx
With this PR, the options which we removed or have hidden in version 3 are also removed from the usage example.
=> [JS] chore: Remove removed generator options from js docs

docs-java/release-notes.mdx
This PR updates the `:::info` box on top of the release notes to now correctly say that Cloud SDK version 3 has reached end of life status and won't receive any updates.
=> Fix: Update the INFO Box on top of the Release Notes

docs-js/features/connectivity/destination.mdx
With this change, the caching option for mTLS certificates will be documented.
Closes https://github.com/SAP/cloud-sdk-backlog/issues/1055
=> JS: add mtls cache to docs

docs-java/features/odata/v2-client.mdx, docs-java/features/odata/v4-client.mdx, docs-java/getting-started.mdx
* OData VDM based modules have been deprecated with 4.17.0
* Mentioning it on the documentation portal is no longer recommended.
=> Remove indicators to deprecated OData VDM based modules

docs-java_versioned_docs/version-v5/faq.mdx
Conflicting dependencies for Spring Boot 3 have been removed from V5, therefore the additional instruction to add in `spring-boot-dependencies` is no longer needed.
=> [V5] FAQ updated

docs-java_versioned_docs/version-v5/getting-started.mdx
This PR adds documentation about how to use the `scp-cf-spring-jakarta` archetype.
=> Java: Add Documentation for the Jakarta Archetype

docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
This PR adds a clarification section on the new `HttpClientAccessor.getHttpClient(Destination)` method.
=> Add clarification on HttpClient getter

docs-java_versioned_docs/version-v5/features/resilience/resilience.mdx, docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
Added line to migration guide about `frameworks` removal and child module movement. Updated dependency ids.
=> [V5] framework module removed

docs-js/guides/sdk-in-browser.mdx, docs-js_versioned_docs/version-v2/guides/sdk-in-browser.mdx
Use NormalModuleReplacementPlugin for internal node modules with node-protocol when compiling for browser.
Applying changes into [Use the SAP Cloud SDK in the Browser](https://sap.github.io/cloud-sdk/docs/js/guides/browser) in current and v2 docs of JavaScript, to include a possible solution for [#1578](https://github.com/SAP/cloud-sdk/issues/1578) where `node:` protocol will fail for bundling towards brower.
=> fix: use NormalModuleReplacementPlugin

docs-java/features/multi-tenancy/thread-context.mdx, docs-java_versioned_docs/version-v5/features/multi-tenancy/thread-context.mdx
SAP/cloud-sdk-java-backlog#156.
This PR changes the documentation of our `RequestHeaderContainer` to no longer mention the header value splitting.
=> refactor: stop splitting header values in RequestHeaderContainer

docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
Extended list of removed modules and apis.
=> [V5] Removed modules/classes extended, re: Multitenancy

docs-js/features/odata/common/batch/configure-serialization.mdx
With this PR, the changes in https://github.com/SAP/cloud-sdk-js/pull/4295 are reflected.
=> chore: Add serialization docs

docs-java_versioned_docs/version-v5/features/multi-tenancy/thread-context.mdx, docs-java_versioned_docs/version-v5/guides/cap-sdk-integration.mdx, docs-java_versioned_docs/version-v5/overview.mdx
Some places were not updated in [chore: minimum CAP version requirement](https://github.com/SAP/cloud-sdk/pull/1599#top)
I updated the min version to be `2.4.0` like the rest of the v5 docs
=> Mention CDS `2.4.0` as min supported version 

docs-java_versioned_docs/version-v5/getting-started.mdx, docs-java_versioned_docs/version-v5/guides/linux-how-to.mdx, docs-java_versioned_docs/version-v5/guides/logging-overview.mdx, docs-java_versioned_docs/version-v5/guides/spring-boot-war-deployment.mdx
From [Rename jakarta archetype to spring-boot3#356](https://github.com/SAP/cloud-sdk-java-backlog/issues/356)
The v5 docs only mention only the new archetype.
Reviewers make sure that all mentions of old archetypes are gone.
=> Renamed spring archetype

docs-java_versioned_docs/version-v5/guides/5.0-upgrade.mdx
This change is part of [this comment](https://github.com/SAP/cloud-sdk/pull/1500#discussion_r1312733781) and [[Documentation] Document new ServiceBinding Connectivity API](https://github.com/SAP/cloud-sdk-java-backlog/issues/178#top)
- I added the missing deprecated class to the v5 migration guide
- It merges on Johannes' PR because I need to link to his page of the replacement API.
- I also added line breaks to make the table more readable, otherwise you have no idea that the comment section exists
=> Added `ScpCfServiceDestinationLoader` to the migration guide

docs-java/guides/5.0-upgrade-steps.mdx
From the support issue https://github.wdf.sap.corp/MA/sdk/issues/8683
Should I add this change to all Abstract destinations in the table?
=> Java migration guide added replacement for `AbstractHttpDestination`

docs-java/guides/5.0-upgrade-steps.mdx
The service binding lib doesn't replace `getVcapApplication`, we need to add a code snippet to help customers migrate
=> [Java] Added replacement for `getVcapApplication`

docs-java/features/odata/generator.mdx
The version number was outdated on the v5 docs.
=> Removed version tag from OData generator

docs-java_versioned_docs/version-v4/release-notes/release-notes-15-to-29.mdx
Adding release notes for `4.29`
To be merged after `4.29` is available on Maven central.
=> [Java] Add release notes for 4.29.0 

docs-java/features/multi-tenancy/thread-context.mdx
Mention native compatibility of virtual threads with Cloud SDK.
https://github.com/SAP/cloud-sdk-java-backlog/issues/369
=> Java virtual threads compatibility with ThreadContextExecutor API

docs-java/features/multi-tenancy/thread-context.mdx
This PR refactors our documentation about multitenancy so that it no longer mentions the `Zone` concept.
=> refactor: Remove Mentions of `Zone` Concept

docs-java_versioned_docs/version-v4/release-notes/release-notes-15-to-29.mdx
Added release notes for 4.30.0, also too lazy to create a new `release-notes-30-to-44.mdx` file
=> Java release notes 4.30.0

docs-java/environments/kyma.mdx, docs-java/faq.mdx, docs-java/features/connectivity/001-btp-destination-service.mdx, docs-java/features/connectivity/003-service-bindings.mdx, docs-java/features/connectivity/004-http-destinations.mdx, docs-java/features/connectivity/005-http-client.mdx, docs-java/guides/5.0-upgrade-steps.mdx, docs-java/guides/spring-boot-war-deployment.mdx, docs-java/release-notes/release-notes-0-to-14.mdx, docusaurus.config.js, sidebarsDocsJava.js, src/sap/sdk-data/data.js
Follow-up of #1728 
This PR replaces links that pointed to the old Sonatype UI for our modules.
=> fix: replace maven central search links for our modules

docs-java/features/odata/v2-client.mdx, docs-java/features/odata/v4-client.mdx
This PR adds a new section to both our OData v2 and v4 docs about how to correctly handle CSRF tokens when executing requests in parallel.
Furthermore, the section also summarizes our current knowledge about why this is needed in the first place.
=> docs: CSRF Token Handling in Multi-Threaded Workloads

docs-java/features/odata/generator.mdx, docs-java_versioned_docs/version-v4/features/odata/generator.mdx, docs-java_versioned_docs/version-v4/features/rest/generate-rest-client.mdx
Found some minor typos in the generator docs. It should be `com.sap.cloud.sdk.datamodel` instead of `om.sap.cloud.datamodel` to work correctly.
=> fix: typo in generator doc

docs-java/features/connectivity/003-service-bindings.mdx
Fixes a typo in the service binding format for IAS backed services.
(For reference: [here](https://github.com/SAP/cloud-sdk-java/blob/main/cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/IdentityAuthenticationServiceBindingDestinationLoader.java#L124) is the corresponding implementation in the SDK)
=> fix: Typo in Service Binding Format

docs-java/features/connectivity/003-service-bindings.mdx, docs-java/release-notes/release-notes-0-to-14.mdx
At the time of the release the docs weren't available yet, thus adding it now retroactively..
=> Java: Retroactively add release notes for IAS support

docs-js/features/common/custom-request-config-note.mdx
While investigating SAP/cloud-sdk-backlog#1187, I found out that the documentation for **Setting a Custom Request Configuration** was not updated fully after `method` was removed from `defaultDisallowedKeys` in `http-request` to support custom http request method [in this PR](https://github.com/SAP/cloud-sdk-js/pull/2303). 
This update removes the `method` option from the disallowed overwrites to align with the above mentioned PR.
=> Javascript: Custom request config default disallowed keys

docs-java/features/connectivity/003-service-bindings.mdx, docs-js/guides/sdk-in-browser.mdx
As we dropped our frontend E2E tests, we no longer actively support it.
This PR adds a warning to our frontend guide.
=> chore: add warning for frontend usage

docs-java/guides/5.0-upgrade-steps.mdx
Some classes were renamed in v5 but not mentioned in the upgrade guide.
=> [Java] Added missing classes in upgrade guide

docs-js/features/openapi/execute-openapi-request.mdx
DRAFT
Added documentation for in header parameters in OpenAPI spec that was implemented in SAP/cloud-sdk-js#4708.
=> Javascript: Add entry for header parameters in OpenAPI request

docs-js/features/connectivity/destination.mdx, docs-js/features/mail-client/mail-client.mdx, docs-js/guides/bas-external-system.mdx, docs-js_versioned_docs/version-v1/features/connectivity/destination-cache-isolation.mdx, docs-js_versioned_docs/version-v1/features/connectivity/destination.mdx, docs-js_versioned_docs/version-v1/guides/bas-external-system.mdx, docs-js_versioned_docs/version-v2/features/connectivity/destination-cache-isolation.mdx, docs-js_versioned_docs/version-v2/features/connectivity/destination.mdx, docs-js_versioned_docs/version-v2/guides/bas-external-system.mdx
This PR relates to our latest addition of multi-tenancy in on-premise mail destinations.
See: https://github.com/SAP/cloud-sdk-js/pull/4808
I also took the liberty to unify the spelling of the  `JWT` placeholder.
=> chore: Add mail multi tenancy documentation

CONTRIBUTING.md
AI/gen-ai-hub-sdk-js-backlog#140.
Reference GenAI contribution guidelines as requested by OSPO.
=> chore: Reference GenAI contribution guidelines

docs-js/features/connectivity/destination.mdx
This PR describes how to use the newly implemented `transformServiceBindingToClientCredentialsDestination` function.
=> chore: Add documentation for the transformServiceBindingToClientCredentialsDestination function

docs/about.mdx
Removed the CAP project diagram because the file went missing. Could not find the file again.
=> Remove CAP project diagram

.eslintrc.js
Currently, the `lint:fix` command fails in `main` with a syntax error in `static/api/v3/assets/main.js`.
But, these are minified files which have been generated, linting is not required to be run on these folders. 
This PR excludes these folders from linting.
=> fix: Ignore linting generated & minified files

docs-js/features/odata/execute-odata-request.mdx, docs-js_versioned_docs/version-v3/features/openapi/execute-openapi-request.mdx, docs-js_versioned_docs/version-v3/features/openapi/generate-openapi-client.mdx
Adding documentation for `setBasePath` and  `basePath` support in `options-per-service.json` file.
Changes for v3, new version `3.25.0` already released.
~**If you are working on the Java v4 docs, remember to also apply the changes to v5**~
=> [JS] Add documentation for setting custom base path (v3)

docs-js/features/connectivity/destination.mdx
https://github.com/SAP/cloud-sdk-js/issues/5517
The current usage for using the `serviceBindingTransformFn` function is wrong. Also improved the overall doc which was confusing to the user.
=> Improve JS `getDestinationFromServiceBinding()` doc

docs-js/features/connectivity/destination.mdx
Relates to SAP/ai-sdk-js-backlog#192
We disable `iasToXsuaaTokenExchange` by default in v4. Updating the docs.
=> (JS) Update default value of `iasToXsuaaTokenExchange` to `false` in V4 documentation

docs-js/release-notes.mdx, docs-js_versioned_docs/version-v3/release-notes.mdx
Release notes for JS 4.0.1 and 3.26.4 were missing.
=> docs: Add missing release note for JS 4.0.1 and 3.26.4
